apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::443502619094:role/eksctl-eksdemo1-nodegroup-eksdemo-NodeInstanceRole-EWL5B2BDLGT1
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::443502619094:user/novelirs
      username: novelirs
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-04T10:18:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3173"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9626ff65-0278-4981-ae81-a4e57518bc83
