apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirat-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirat-nginx
  template:
    metadata:
      name: mirat-nginx
      labels:
        app: mirat-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

