apiVersion: v1
kind: PersistentVolume
metadata:
  name: mirat-persistentvolume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data
